# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c7efa5a61a91299d7f0da3c65e0920ba3aa33f9834d8b923df693209b72dbae4c8647b3d0b69446cf88ae44de11c8089d68ff06660949ffb976b409dacd76b5

test:
  secret_key_base: 5fe828c6ea784e121a17570d52a4c75dd060ff2d6e76e80658777ac1f37c8af1488df1805ea68aefbd57cb8e09ae6a352665da81a36a1ca9b1a81e51bb31df63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
